### ISSUE TITLE
Endless failed request  polling loop

### ISSUE THREAD

**Issue by Gudahtt** [MetaMask/eth-block-tracker#163]
The polling block tracker has been observed being stuck in an endless loop (e.g. https://github.com/MetaMask/metamask-extension/issues/17040).

I was able to reproduce this scenario by using MetaMask extension to switch to a network that will fail to respond to requests. This results in an endless loop of failed requests, even after switching away (i.e. even after there are no more listeners). In the debugger I confirmed that the only active listeners were internal to the block tracker itself ([specifically this listener](https://github.com/MetaMask/eth-block-tracker/blob/861683ef68b866c0f35c72bb477caf3579f40e38/src/BaseBlockTracker.ts#L65)).

**Comment by Gudahtt** [comment]
I was still able to reproduce this bug on v9.0.3

**Comment by mcmire** [comment]
In the [PR](https://github.com/MetaMask/eth-block-tracker/pull/166#issuecomment-1659289779) that is linked to in the timeline above and was closed, I made this comment:

> @Gudahtt and I had a discussion and we feel like we can solve this a different way that doesn't involve listening to `latest` in any form.

@Gudahtt Do you still think following that route would be a proper fix here?

**Comment by Gudahtt** [comment]
Unfortunately I don't recall the details of that solution

**Comment by mcmire** [comment]
For clarity, a solution here would be to figure out a way to have the block tracker ignore internally-added listeners. More details here: https://consensys.slack.com/archives/C06FXU326RL/p1718910083555919?thread_ts=1718130645.943409&cid=C06FXU326RL
