### ISSUE TITLE
Emit errors

### ISSUE THREAD

**Issue by IstoraMandiri** [MetaMask/eth-block-tracker#23]
Currently `block-tracker` will handle error events itself using `console.error`.

https://github.com/MetaMask/eth-block-tracker/blob/master/lib/index.js#L48

Previously, with provider-engine, an `error` event was emitted, which allowed me to hook into this to update the UI to show a connection failure.

Can we add this functionality back? I'll submit a PR.

**Comment by hitchcott** [comment]
Update: I've figured out I don't need this for the initial connection, as I can just use.

```
engine._blockTracker.start().catch((err) => console.log('connection error'));
```

However, for [other errors](https://github.com/MetaMask/eth-block-tracker/blob/master/lib/index.js#L124) (after the initial connection), this still might be useful. Still worth a PR?

**Comment by kumavis** [comment]
yeah i would say we should also emit them
polling errors would be lost otherwise

**Comment by Azier777** [comment]
I second that

**Comment by mcmire** [comment]
Do we think this is still an issue?

**Comment by mcmire** [comment]
Closing this due to lack of response, but happy to reopen if we have more information about this. It's possible this may come back up later, too.
