### ISSUE TITLE
Move babelify to dev dependency

### ISSUE THREAD

**Issue by krzkaczor** [MetaMask/eth-block-tracker#26]
Is there any reason why `babelify` is dependency (not dev-dependency)? Our package `ledger-wallet-provider` (indirectly) depends on `eth-block-tracker` and thus on it depends on babelify, babel-core etc.  which is clearly wrong to me.

cc: @banciur

**Comment by danfinlay** [comment]
As part of its build process, `dev-dependencies` is where this seems like it belongs. This does not get bundled in the exports, so what's the problem?

**Comment by banciur** [comment]
It's not in `devDependencies` but in `dependencies` - https://github.com/MetaMask/eth-block-tracker/blob/master/package.json#L15

**Comment by danfinlay** [comment]
Oh sorry, I misread, was doing a lot of issues. I think we would gladly merge this simple PR.

**Comment by kumavis** [comment]
we actually aren't even using it. removed it.
