### ISSUE TITLE
polling does not continue if created offline

### ISSUE THREAD

**Issue by frankiebee** [MetaMask/eth-block-tracker#27]
when a block tracker is created offline and fails to fetch it throws an error in the form of a uncaught promise. This stops polling and does not resume polling this can be an issue the only way it seems to resume polling is if you the stop and start it again when back online.

**Comment by willianr2304** [comment]
Willianrampanelli@gmail.com

**Comment by mcmire** [comment]
I'm inclined to close this issue as I don't think this is a problem due to the error handling that now takes place within `PollingBlockTracker.prototype._synchronize`. Any thoughts?

**Comment by mcmire** [comment]
Closing due to lack of response, but happy to reopen if this is still a problem.
