### ISSUE TITLE
Eth-Block-Tracker fails when used with a provider created by Web3.js beta 55

### ISSUE THREAD

**Issue by adrianmcli** [MetaMask/eth-block-tracker#40]
I've made a reproduction repo [here](https://github.com/adrianmcli/repro-eth-block-tracker-bug) with an Infura provider as well as a Ganache provider.

I suspect it has something to do with the way Eth-Block-Tracker expects the provider object to behave.

**Comment by whymarrh** [comment]
I'm going to close this for now, please feel free to open a new issue if needed.

This is for a beta version of the library, please test against stable versions if possible.
