### ISSUE TITLE
Error while installing package

### ISSUE THREAD

**Issue by arnoudcommandeur** [MetaMask/eth-block-tracker#43]
When I try to install the package via: npm i async-eventemitter

I recieve the following error:

npm ERR! code ENOLOCAL
npm ERR! Could not install from "node_modules\eth-tx-summary\node_modules\eth-block-tracker\async-eventemitter@github:ahultgren\async-eventemitter#fa06e39e56786ba541c180061dbf2c0a5bbf951c" as it does not contain a package.json file.

Anyone an idea how to fix this issue?

**Comment by whymarrh** [comment]
Are you still running into this issue?

**Comment by arnoudcommandeur** [comment]
Hi @whymarrh, thanks for your reply. Currently this is nog an issue anymore. I will close this issue.

**Comment by andydemeulemeester** [comment]
> When I try to install the package via: npm i async-eventemitter
> 
> I recieve the following error:
> 
> npm ERR! code ENOLOCAL npm ERR! Could not install from "node_modules\eth-tx-summary\node_modules\eth-block-tracker\async-eventemitter@github:ahultgren\async-eventemitter#fa06e39e56786ba541c180061dbf2c0a5bbf951c" as it does not contain a package.json file.
> 
> Anyone an idea how to fix this issue?

How did you solved that issue?
