### ISSUE TITLE
Question: is SubscribeBlockTracker safe to use?

### ISSUE THREAD

**Issue by sterlu** [MetaMask/eth-block-tracker#69]
I noticed the SubscribeBlockTracker while digging around packages trying to lower the number of eth_getBlockByNumber requests in web3-provider-engine. Is it safe to use? Seems to be working. However it's not exported, nor mentioned anywhere in the docs. 

Tagging @jamespic as he seems to have implemented it 2 years ago - hope you don't mind the ping.

**Comment by jamespic** [comment]
Well, it was safe to use when I wrote it two years ago 😉.

If I remember rightly, at the time I was interested in interesting with API endpoints that support push subscriptions, like websockets and TCP IPC. But the project I was using it for ended up going a different way (I'm not using it now), and a lot has changed in this space in those two years. So if it were me, I'd test it before using it on a real project.

**Comment by mspaansen** [comment]
😀

**Comment by mcmire** [comment]
There are tests for this, so in that sense, we know it works, but we still don't use it for anything at MetaMask. I'd echo @jamespic's advice with the expectation that it may go away at some point in the future. If people still need it after that point, then we can accommodate another solution.
