### ISSUE TITLE
Consider: Exclude `bundle.js` from git repo?

### ISSUE THREAD

**Issue by danfinlay** [MetaMask/eth-block-tracker#8]
We have a pre-publish hook for building, so maybe we don't need the build in the repo.  Thoughts?

**Comment by tmashuang** [comment]
I thought of this afterwards. Also, I am not including the hexUtils with the bundle. Was going to move the build and src to their respective directory and move the build in ignore.

**Comment by flyswatter** [comment]
Yeah, it's tempting.  I wonder if anyone would object.  I think if anyone is installing with `bower` it might interfere with that?

**Comment by kumavis** [comment]
we dont currently include it

**Comment by kumavis** [comment]
let me correct that, currently we build first and then publish

**Comment by kumavis** [comment]
or whatever, theres no bundle.js just the dist dir
